# DISPLAY OPTIONS
TARGET_FRAMERATE = 60
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

# WINDOW OPTIONS
WINDOW_CAPTION = "Pyñata Engine"
WINDOW_ICON_PATH = ""

# AUDIO
AUDIO_SAMPLING_RATE = 44100
AUDIO_BUFFER_SIZE = 512

MASTER_VOLUME = 1

DEFAULT_MIN_FADEOUT_DISTANCE = 200
DEFAULT_MAX_FADEOUT_DISTANCE = 600
