# DISPLAY OPTIONS
TARGET_FRAMERATE = 60
WINDOW_WIDTH = 512
WINDOW_HEIGHT = 512

# WINDOW OPTIONS
WINDOW_CAPTION = "Pyñata Engine"
WINDOW_ICON_PATH = ""

# AUDIO
AUDIO_SAMPLING_RATE = 44100
AUDIO_BUFFER_SIZE = 512
